[package]
name = "lox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rlox"

[dependencies]
anyhow = "1"
miette = { version = "7.2", features = ["fancy"] }
rustyline = "12"
thiserror = "1"
chrono = "0.4.38"

[dev-dependencies]
pretty_assertions = "1.4.0"
