[package]
name = "lox_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
lox_source = { path = "../lox_source" }
lox_bytecode = { path = "../lox_bytecode" }
thiserror = "1"

[dev-dependencies]
insta = { version = "1.42.1", features = ["yaml"] }
