[package]
name = "lox_compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
lox_source = { path = "../lox_source" }
lox_vm = { path = "../lox_vm" }
thiserror = "1"

[dev-dependencies]
insta = { version = "1.42.1", features = ["yaml"] }
