[package]
name = "lox_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
lox_source = { path = "../lox_source" }
lox_bytecode = { path = "../lox_bytecode" }
lox_value = { path = "../lox_value" }
jiff = "0.2.4"
